-- ============================================================
-- BrontoloBike – Schema database
-- Eseguire nel SQL Editor di Supabase (una volta sola)
-- ============================================================

-- -------------------------
-- STAGIONI
-- -------------------------
CREATE TABLE IF NOT EXISTS stagioni (
  id        SERIAL PRIMARY KEY,
  anno      INTEGER NOT NULL UNIQUE,
  attiva    BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO stagioni (anno, attiva) VALUES (2027, true);

-- -------------------------
-- ATLETI
-- -------------------------
CREATE TABLE IF NOT EXISTS atleti (
  id                  TEXT PRIMARY KEY,
  nome_cognome        TEXT NOT NULL,
  genere              TEXT NOT NULL CHECK (genere IN ('Uomo', 'Donna')),
  categoria_corrente  TEXT NOT NULL CHECK (categoria_corrente IN ('AMATORI', 'CICLOTURISTI')),
  categoria_prossima  TEXT NOT NULL CHECK (categoria_prossima IN ('AMATORI', 'CICLOTURISTI')),
  user_id             UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO atleti (id, nome_cognome, genere, categoria_corrente, categoria_prossima) VALUES
  ('ATL_1001', 'Abate Orazio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1002', 'Acquaviva Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1003', 'Acquistapace Lucia', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1004', 'Airaghi Claudio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1005', 'Alampi Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1006', 'Alemanni Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1007', 'Amorese Angelo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1008', 'Andreoni Mario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1009', 'Antonini Guido', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1010', 'Anzolini Elena', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1011', 'Armanini Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1012', 'Bacci Marco Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1013', 'Bagnati Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1014', 'Bagorda Francesco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1015', 'Ballini Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1016', 'Balzarotti Enrico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1017', 'Barbaini Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1018', 'Barbera Giuliano', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1019', 'Barbierato Marco', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1020', 'Barone Paolo', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1021', 'Bartezzaghi Ivan Ernesto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1022', 'Bazzetta Luca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1023', 'Bazzi Maurizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1024', 'Belletti Vittorio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1025', 'Belloni Simone', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1026', 'Belluco Loris Luigi', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1027', 'Belluschi Cesare', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1028', 'Bencivenga Claudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1029', 'Benedetti Stefania', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1030', 'Beretta Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1031', 'Bergonzi Pierriccardo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1032', 'Besana Cristina', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1033', 'Bettolini Giancarlo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1034', 'Bianchi Maria Chiara', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1035', 'Bianchi Maurizio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1036', 'Bianchi Roberta', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1037', 'Bianchini Francesca', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1038', 'Biancolin Luciano', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1039', 'Bienati Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1040', 'Boarella Luigi', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1041', 'Bocca Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1042', 'Bodini Luca Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1043', 'Bonassi Fabio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1044', 'Boneschi Claudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1045', 'Bonuso Carmine', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1046', 'Borella Monica', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1047', 'Borgia Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1048', 'Borgo Enrico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1049', 'Borgonovi Germano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1050', 'Borini Fabio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1051', 'Borsani Gabriele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1052', 'Bossi Edoardo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1053', 'Botta Veneziale Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1054', 'Botter Massimo', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1055', 'Bovolenta Christian', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1056', 'Bragalini Giuliano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1057', 'Bragalini Tiziano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1058', 'Bramani Carlo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1059', 'Brandolese Davide Domenico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1060', 'Bresciani Sergio Diomiro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1061', 'Brunetti Marcello', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1062', 'Bruschi Manuela', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1063', 'Bussi Claudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1064', 'Buttice Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1065', 'Cagnola Francesco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1066', 'Cairati Giampietro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1067', 'Cairati Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1068', 'Callegaro Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1069', 'Calzolari Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1070', 'Campana Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1071', 'Campanella Gaetano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1072', 'Candiani Claudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1073', 'Cantini Marina', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1074', 'Cantini Silvia', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1075', 'Cantoni Stefano', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1076', 'Canziani Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1077', 'Carbone Vincenzo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1078', 'Cardellini Ilario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1079', 'Carnaghi Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1080', 'Caronelli Daniele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1081', 'Caruso Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1082', 'Castiglioni Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1083', 'Catalano Gaspare', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1084', 'Cataldo Cristina', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1085', 'Cavalletto Giannino', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1086', 'Cavalli Marzia', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1087', 'Cecere Francesca', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1088', 'Ceffa Alessio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1089', 'Ceresa Andrea Mario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1090', 'Ceriani Giorgio Carlo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1091', 'Chindamo Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1092', 'Ciaburri Luigi', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1093', 'Cislaghi Elena', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1094', 'Cocina Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1095', 'Cocozzello Rocco Michele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1096', 'Colombo Aldo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1097', 'Colombo Alessandra', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1098', 'Colombo Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1099', 'Colombo Angelo Mario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1100', 'Colombo Fabrizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1101', 'Colombo Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1102', 'Comincioli Garghetti Giovanni Carlo', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1103', 'Conti Sara', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1104', 'Cornacchia Marco', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1105', 'Cossu Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1106', 'Cozzoli Gian Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1107', 'Craici Christian', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1108', 'Crespi Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1109', 'Cribiu'' Antonio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1110', 'Curti Dario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1111', 'Curti Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1112', 'Damiano Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1113', 'Damiano Elia', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1114', 'Daverio Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1115', 'Daverio Fabio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1116', 'De Giuli Federico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1117', 'De Lorenzi Alessandro', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1118', 'De Poli Christian', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1119', 'De Santis Luigi', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1120', 'De Vecchi Danilo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1121', 'De Vecchi Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1122', 'Delbo'' Esmeralda', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1123', 'Delia Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1124', 'Dell Torre Michele', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1125', 'Dell''Utri Marcella', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1126', 'Della Vedova Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1127', 'Delle Donne Giordano', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1128', 'Dettori Salvatore', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1129', 'Di Ciero Gino', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1130', 'Di Marco Danilo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1131', 'Di Rocco Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1132', 'Di Sabatino Gabriele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1133', 'Di Vincenzo Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1134', 'Dominici Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1135', 'Donati Francesco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1136', 'Dovio Alessandro', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1137', 'Duyver Jacques', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1138', 'Elefante Alberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1139', 'Fabiano Raffaele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1140', 'Falco Ferdinando', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1141', 'Falcone Mauro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1142', 'Fanutza Maurizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1143', 'Fattore Michele', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1144', 'Ferlauto Domenico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1145', 'Ferrari Federica', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1146', 'Ferrari Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1147', 'Ferrari Sergio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1148', 'Ferrero Silvio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1149', 'Filippucci Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1150', 'Filisetti Luca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1151', 'Filisetti Rossana', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1152', 'Finotti Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1153', 'Finotti Mattia', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1154', 'Fiorani Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1155', 'Foini Roberto Angelo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1156', 'Forasacco Francesca', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1157', 'Forloni Guglielmo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1158', 'Fornillo Saverio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1159', 'Franza Giuseppe', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1160', 'Frasca Paola', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1161', 'Furbo Giuseppe', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1162', 'Gagliardi Raffaele', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1163', 'Galimberti Andrea Federico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1164', 'Galimberti Giorgio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1165', 'Gallana Valter', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1166', 'Galli Emanuela Barbara', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1167', 'Gallini Edoardo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1168', 'Gallone Maurizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1169', 'Gambacorta Maurizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1170', 'Garavaglia Filippo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1171', 'Garavaglia Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1172', 'Garavaglia Giuliana', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1173', 'Garavaglia Luisella', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1174', 'Garavaglia Matteo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1175', 'Garlaschelli Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1176', 'Garofolo Fabrizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1177', 'Garziano Giovan Battista', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1178', 'Gemmetto Walter', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1179', 'Genovese Nunziata', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1180', 'Ghidoli Linda', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1181', 'Ghidoni Filippo Lapo Maria', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1182', 'Ghitti Matteo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1183', 'Giana Matteo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1184', 'Gianno Nicola', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1185', 'Giorrandello Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1186', 'Giudice Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1187', 'Gori Alessandro', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1188', 'Gorini Mauro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1189', 'Gozzi Elisa', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1190', 'Grassi Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1191', 'Gritti Andrea', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1192', 'Gritti Mario', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1193', 'Guariento Alberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1194', 'Guerra Loris', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1195', 'Guolo Fabbrizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1196', 'Guzzon Attilio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1197', 'Iannacci Claudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1198', 'Ingiann Daniele', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1199', 'Lazzari Sara', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1200', 'Learchi Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1201', 'Lenoci Cosimo Dario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1202', 'Leone Carmine', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1203', 'Leoni Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1204', 'Leotardi Marco Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1205', 'Leto Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1206', 'Locatelli Dario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1207', 'Locati Arianna', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1208', 'Locorotondo Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1209', 'Lomuoio Luca Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1210', 'Lonati Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1211', 'Longone Massimiliano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1212', 'Lucini Claudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1213', 'Macchi Guido', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1214', 'Maglio Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1215', 'Magnaghi Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1216', 'Magnani Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1217', 'Malacalza Davide Mauro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1218', 'Malini Luca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1219', 'Malivindi Francesco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1220', 'Maltagliati Elio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1221', 'Manara Maurizio Camillo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1222', 'Marangoni Matteo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1223', 'Marinello Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1224', 'Marzio Nicola Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1225', 'Masiero Francesco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1226', 'Masiero Renzo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1227', 'Massara Christian', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1228', 'Maulini Thomas', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1229', 'Mauro Valentino', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1230', 'Mazzante Loris', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1231', 'Mazzeo Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1232', 'Mazzola Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1233', 'Mazzoli Fabrizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1234', 'Megliola Pasquale', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1235', 'Mercanti Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1236', 'Merisi Maurizio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1237', 'Meroni Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1238', 'Milanato Valerio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1239', 'Mittino Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1240', 'Moda Andrea', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1241', 'Montagna Gilberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1242', 'Montaruli Francesco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1243', 'Moschi Mauro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1244', 'Motolese Daniele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1245', 'Mugnai Stefano', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1246', 'Mulas Emanuel', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1247', 'Mura Gianluca', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1248', 'Naranzoni Daniele', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1249', 'Negri Giampaolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1250', 'Nera Emilio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1251', 'Nichele Tiziano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1252', 'Nicola Raffaella', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1253', 'Noe'' Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1254', 'Noe'' Antonio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1255', 'Noe'' Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1256', 'Noe'' Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1257', 'Novati Carlo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1258', 'Novelli Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1259', 'Noviello Luca Franco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1260', 'Oriani Aldo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1261', 'Oriani Lea', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1262', 'Orsi Simone Mattia', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1263', 'Osio Marco Primo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1264', 'Padovan Manuela', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1265', 'Pagani Albino', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1266', 'Paleari Elio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1267', 'Paolini Francesca', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1268', 'Pappalardo Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1269', 'Parati Fabio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1270', 'Parenza Manuel Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1271', 'Paridi Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1272', 'Parini Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1273', 'Parmeggiani Daniele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1274', 'Parmigiani Fiorenzo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1275', 'Parmigiani Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1276', 'Pasini Manola Erminia', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1277', 'Patriarca Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1278', 'Pedotti Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1279', 'Pellegrino Giovanni', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1280', 'Perotti Gianni', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1281', 'Pesenti Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1282', 'Pesenti Enrico', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1283', 'Pezzotti Cristofero', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1284', 'Piatti Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1285', 'Pioldi Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1286', 'Pipoli Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1287', 'Piredda Matteo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1288', 'Poletti Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1289', 'Porta Marianna', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1290', 'Pozzato Samuele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1291', 'Pozzi Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1292', 'Prati Ivano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1293', 'Pre'' Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1294', 'Provasi Fabrizio', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1295', 'Pulici Stefania', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1296', 'Pulvirenti Alfio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1297', 'Raimondi Matteo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1298', 'Rapisarda Alan Miky', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1299', 'Rapisarda Orazio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1300', 'Ravazzani Lorena', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1301', 'Re Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1302', 'Rebeschi Mauro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1303', 'Renna Cosimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1304', 'Restelli Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1305', 'Restelli Massimiliano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1306', 'Riccardi Guglielmo', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1307', 'Ricci Mirella', 'Donna', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1308', 'Rinaldi Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1309', 'Riva Carlo Alberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1310', 'Roccaro Giovanni Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1311', 'Roda Fausto', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1312', 'Roda Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1313', 'Rolfi Simone', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1314', 'Roncaletti Belinda', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1315', 'Rondena Sergio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1316', 'Rossi Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1317', 'Rossi Mauro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1318', 'Rovati Luciano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1319', 'Rovida Igor', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1320', 'Russo Graziano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1321', 'Sagliocco Fabio Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1322', 'Sala Carlo Roberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1323', 'Santa Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1324', 'Sarto Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1325', 'Sassone Mattia', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1326', 'Sbro'' Ivan Ernesto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1327', 'Schidoni Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1328', 'Scolari Paolo Maria', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1329', 'Serra Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1330', 'Sgualdi Piergiuseppe', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1331', 'Sisti Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1332', 'Sitta Donato', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1333', 'Sosero Pierangelo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1334', 'Sozzi Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1335', 'Spiller Ermenegildo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1336', 'Spiller Jeurgen', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1337', 'Spotti Sergio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1338', 'Stankevych Vira', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1339', 'Stefanelli Antonio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1340', 'Stellini Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1341', 'Stellini Lorenzo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1342', 'Tarantola Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1343', 'Tassan Stefano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1344', 'Temporali Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1345', 'Thian Babacar', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1346', 'Tizzoni Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1347', 'Tondini Dario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1348', 'Tornese Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1349', 'Torre Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1350', 'Torresan Lerri', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1351', 'Trere Giovanni', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1352', 'Trevisan Valentina', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1353', 'Troiano Giuseppe', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1354', 'Ugolotti Aldo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1355', 'Valieri Monica', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1356', 'Valisi Davide', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1357', 'Vallini Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1358', 'Vantellino Marco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1359', 'Vecchi Daniele', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1360', 'Vella Dario', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1361', 'Venegoni Alberto', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1362', 'Venturini Paolo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1363', 'Verita'' Luciano', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1364', 'Vigano'' Vincenzo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1365', 'Vignati Cesare', 'Uomo', 'CICLOTURISTI', 'CICLOTURISTI'),
  ('ATL_1366', 'Vitari Alessandro', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1367', 'Volpi Fabio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1368', 'Zaccheddu Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1369', 'Zaffiro Nadia', 'Donna', 'AMATORI', 'AMATORI'),
  ('ATL_1370', 'Zamproni Omar', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1371', 'Zangrossi Imero', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1372', 'Zanini Massimo', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1373', 'Zanoni Giovanni', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1374', 'Zenel Klaudio', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1375', 'Zetta Andrea', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1376', 'Zetti Franco', 'Uomo', 'AMATORI', 'AMATORI'),
  ('ATL_1377', 'Zonca Ivan', 'Uomo', 'AMATORI', 'AMATORI')
ON CONFLICT (id) DO NOTHING;

-- -------------------------
-- TIPOLOGIE EVENTO
-- -------------------------
CREATE TABLE IF NOT EXISTS tipologie_evento (
  id                    SERIAL PRIMARY KEY,
  nome                  TEXT NOT NULL UNIQUE,
  coefficiente_km       NUMERIC(4,1) NOT NULL DEFAULT 1,
  punti_fissi           INTEGER,
  ignora_km_dislivello  BOOLEAN NOT NULL DEFAULT false
);

INSERT INTO tipologie_evento (nome, coefficiente_km, punti_fissi, ignora_km_dislivello) VALUES
  ('Gran/Medio Fondo',             2,  NULL,  false),
  ('Randonnée fino a 120Km',       2,  NULL,  false),
  ('Randonnée oltre i 120Km',      1,  NULL,  false),
  ('Pedalata Cicloturistica',      2,  NULL,  false),
  ('Brevetto Permanente Strada',   1,  NULL,  false),
  ('Brevetto Permanente Gravel',   3,  NULL,  false),
  ('Percorso con Credenziale',     1,  NULL,  false),
  ('Ciclocross',                   4,  NULL,  false),
  ('MTB',                          4,  NULL,  false),
  ('Gravel',                       3,  NULL,  false),
  ('Gara in Circuito (CRIT)',      4,  NULL,  false),
  ('Gravel di GRAvelAND',          5,  NULL,  false),
  ('Trail',                        1,  NULL,  false),
  ('Brontolo Bike Day',           15,  NULL,  false),
  ('Uva Fragola',                 15,  NULL,  false),
  ('Bike Camp Livigno',            1,  1000,  true)
ON CONFLICT (nome) DO NOTHING;

-- -------------------------
-- EVENTI
-- -------------------------
CREATE TABLE IF NOT EXISTS eventi (
  id            SERIAL PRIMARY KEY,
  nome          TEXT NOT NULL,
  data_evento   DATE,
  stagione_id   INTEGER NOT NULL REFERENCES stagioni(id),
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- -------------------------
-- PERCORSI (corto/medio/lungo di un evento)
-- -------------------------
CREATE TABLE IF NOT EXISTS percorsi (
  id              SERIAL PRIMARY KEY,
  evento_id       INTEGER NOT NULL REFERENCES eventi(id) ON DELETE CASCADE,
  nome_percorso   TEXT NOT NULL DEFAULT 'Unico',
  km              NUMERIC(6,1) NOT NULL,
  dislivello_m    INTEGER NOT NULL DEFAULT 0
);

-- -------------------------
-- REGISTRAZIONI
-- -------------------------
CREATE TABLE IF NOT EXISTS registrazioni (
  id              SERIAL PRIMARY KEY,
  atleta_id       TEXT NOT NULL REFERENCES atleti(id),
  percorso_id     INTEGER NOT NULL REFERENCES percorsi(id),
  stagione_id     INTEGER NOT NULL REFERENCES stagioni(id),
  completato      BOOLEAN NOT NULL DEFAULT true,
  km_effettivi    NUMERIC(6,1),
  dislivello_eff  INTEGER,
  punti           INTEGER NOT NULL DEFAULT 0,
  note            TEXT,
  registrato_da   UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (atleta_id, percorso_id, stagione_id)
);

-- -------------------------
-- ROW LEVEL SECURITY (base)
-- -------------------------
ALTER TABLE atleti           ENABLE ROW LEVEL SECURITY;
ALTER TABLE stagioni         ENABLE ROW LEVEL SECURITY;
ALTER TABLE tipologie_evento ENABLE ROW LEVEL SECURITY;
ALTER TABLE eventi           ENABLE ROW LEVEL SECURITY;
ALTER TABLE percorsi         ENABLE ROW LEVEL SECURITY;
ALTER TABLE registrazioni    ENABLE ROW LEVEL SECURITY;

-- Lettura pubblica per tutti (anche non autenticati)
CREATE POLICY "Lettura pubblica atleti"           ON atleti           FOR SELECT USING (true);
CREATE POLICY "Lettura pubblica stagioni"         ON stagioni         FOR SELECT USING (true);
CREATE POLICY "Lettura pubblica tipologie"        ON tipologie_evento FOR SELECT USING (true);
CREATE POLICY "Lettura pubblica eventi"           ON eventi           FOR SELECT USING (true);
CREATE POLICY "Lettura pubblica percorsi"         ON percorsi         FOR SELECT USING (true);
CREATE POLICY "Lettura pubblica registrazioni"    ON registrazioni    FOR SELECT USING (true);

-- Scrittura registrazioni: solo utenti autenticati
CREATE POLICY "Inserimento registrazioni auth"    ON registrazioni    FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Modifica registrazioni auth"       ON registrazioni    FOR UPDATE USING (auth.role() = 'authenticated');
